theme: jekyll-theme-cayman
title: <img src="img/AppLogo.png" class="header-logo" /><br />PrismaLog
description: PrismaLog is a simple time log application to track time per task in a story and project.
