theme: jekyll-theme-cayman
title: <img src="img/AppLogo.png" class="header-logo" /><br />PrismaLog
description: PrismaLog is a simple time tracking application to track time per task in a story and project.<br /><br /><a href="https://apps.apple.com/de/app/prismalog/id1486886229"><img src="img/Download-AppStore-135x40.svg" /></a>
